version: "3.9"

services:
  db:
    image: postgres:16-alpine
    container_name: archburgers_db
    hostname: archburgers_db
    restart: "no"   # Sem restart automático por ser um serviço com fins didáticos
    environment:
      POSTGRES_DB: archburgers_catalogo
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: "216hdjkasda%jhjKaA"
      TZ: "America/Sao_Paulo"
    healthcheck:
      test: psql -U pguser -d archburgers_catalogo -c 'select 1'
      interval: 10s
      retries: 5
      start_period: 5s
      timeout: 10s

  app:
    image: gomesrodris/architect-burgers-svc-catalogo:0.0.1
    container_name: svc-catalogo
    restart: "no"
    environment:
      "videosliceapi.datasource.dbUrl": "jdbc:postgresql://archburgers_db/archburgers_catalogo?autoReconnect=true"
      "videosliceapi.datasource.dbUser": pguser
      "videosliceapi.datasource.dbPass": "216hdjkasda%jhjKaA"

    ports:
      - "8092:8092"
    depends_on:
      db:
        condition: service_healthy

  ## TODO : Integrate all services