version: "3.9"

services:
  db:
    image: postgres:16-alpine
    container_name: videoslice_db
    hostname: videoslice_db
    restart: "no"   # Sem restart automático por ser um serviço com fins didáticos
    environment:
      POSTGRES_DB: videoslice
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: "216hdjkasda%jhjKaA"
      TZ: "America/Sao_Paulo"
    healthcheck:
      test: psql -U pguser -d videoslice -c 'select 1'
      interval: 10s
      retries: 5
      start_period: 5s
      timeout: 10s

  aws-localstack:
    image: localstack/localstack:stable
    container_name: aws_localstack
    hostname: localstack.cloud
    restart: "no"
    environment:
      LOCALSTACK_HOST: localstack.cloud:4566
    ports:
      - 54566:4566
    volumes:
      - ./init-localstack.sh:/etc/localstack/init/ready.d/init-localstack.sh

  svc-engine:
    image: dockerhubalancarvalho/fiap-videoslice-svc-engine:0.0.12
    container_name: svc-engine
    restart: "no"
    environment:
      "videoslice.integration.sqs.sqsEndpoint": "http://localstack.cloud:4566"
      "videoslice.integration.s3.s3Endpoint": "http://localstack.cloud:4566"
      "videosliceapi.integration.aws.overrideAwsEndpoint": "http://localstack.cloud:4566"
      
      "videoslice.integration.sqs.videosToBeProcessedQueueName": "videoslice_job_requests"
      "videoslice.integration.sqs.videosToBeProcessedQueueUrl": "http://localstack.cloud:4566/000000000000/videoslice_job_requests"
      "videoslice.integration.sqs.videoStatusQueueName": "videoslice_job_status"
      "videoslice.integration.sqs.videoStatusQueueUrl": "http://localstack.cloud:4566/000000000000/videoslice_job_status"
      
      "videoslice.integration.s3.bucketName": "videoslice-job-requests"

      "AWS_ACCESS_KEY_ID": 000000000000
      "AWS_SECRET_ACCESS_KEY": 000000000000
    depends_on:
      aws-localstack:
        condition: service_started

  svc-web-api:
    image: gomesrodris/fiap-videoslice-svc-web-api:0.0.6
    container_name: svc-web-api
    restart: "no"
    environment:
      "videosliceapi.auth.development-dummy-tokens.enabled": "true"

      "videosliceapi.datasource.dbUrl": "jdbc:postgresql://videoslice_db/videoslice?autoReconnect=true"
      "videosliceapi.datasource.dbUser": "pguser"
      "videosliceapi.datasource.dbPass": "216hdjkasda%jhjKaA"

      "videosliceapi.integration.smtp.enabled": "false"

      "videosliceapi.integration.aws.region": "us-east-1"
      "videosliceapi.integration.cognito.userPoolId": "us-east-1_222222222"
      "videosliceapi.integration.cognito.clientId": "9999999999"
      "videosliceapi.integration.cognito.clientSecret": "9999999999999999999999999999999999"

      "videosliceapi.integration.aws.overrideAwsEndpoint": "http://localstack.cloud:4566"

      "videosliceapi.integration.sqs.videoProcessRequestQueueName": "videoslice_job_requests"
      "videosliceapi.integration.sqs.videoProcessResponseQueueName": "videoslice_job_status"

      "videosliceapi.integration.s3.videoProcessRequestBucketName": "videoslice-job-requests"
      "videosliceapi.integration.s3.videoProcessResultBucketName": "videoslice-job-results"

      "AWS_ACCESS_KEY_ID": 000000000000
      "AWS_SECRET_ACCESS_KEY": 000000000000

    ports:
      - "8090:8090"
    depends_on:
      svc-engine:
        condition: service_started
      db:
        condition: service_healthy

