package com.example.fiap.videosliceapi.domain.utils;

import org.junit.jupiter.api.Test;

import java.time.Instant;

import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * Test class for the {@link Clock} class.
 * Tests the single method localDateTime.
 */
public class ClockTest {

    /**
     * Test the {@link Clock#now()} method.
     * The method returns the current time. 
     * The purpose of this test is check if the method is able to return the current time accurately within a certain limit.
     */
    @Test
    public void testLocalDateTime() {
        Clock clock = new Clock();
        Instant before = Instant.now();
        Instant result = clock.now();
        Instant after = Instant.now();
        //Test that the localDateTime generated by Clock is after the localDateTime before the clock.localDateTime call
        assertTrue(result.isAfter(before) || result.equals(before));
        //Test that the localDateTime generated by Clock is before the localDateTime after the clock.localDateTime call
        assertTrue(result.isBefore(after) || result.equals(after));
    }
}