apiVersion: v1
kind: Service
metadata:
  name: videoslice-svc-web-api-service
spec:
  type: NodePort
  selector:
    app: videoslice-svc-web-api
  ports:
    - protocol: TCP
      port: 8090
      targetPort: 8090
      nodePort: 30081
