apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: svc-web-api-hpa
spec:
  minReplicas: 1
  maxReplicas: 3
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: videoslice-svc-web-api-deployment
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
