name: run-unit-test
run-name: Testing after ${{github.actor}}'s changes
on: push
jobs:
  mvn-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name: Maven Test
        run: mvn test
