name: verify-project-on-pull-request
run-name: Verifying on PR - ${{github.event.pull_request.title}}
on: push  # Temporary while testing!!! - must be only on PR
#  pull_request:
#    types:
#      - opened
#      - synchronize
#      - reopened

jobs:
  mvn-verify-dev-tests-and-integration:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name: Maven Verify
        run: mvn verify

      - name: Upload coverage reports
        if: success() || failure()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-reports
          path: "modules/*/target/site/jacoco-merged-test-coverage-report/*"
          retention-days: 2
